
service: pdf2img

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:PutObjectAcl
    Resource: "arn:aws:s3:::quiztrainer-quiz-images-${self:provider.stage}/*"

functions:
  pdf2img:
    handler: pdf2img.execute
    events:
      - s3:
          bucket: "quiztrainer-quiz-images-${self:provider.stage}"
          event: s3:ObjectCreated:*
          rules:
            - suffix: .pdf
      - cloudwatchLog: '/aws/lambda/pdf2img'

    environment:
      BUCKET: "quiztrainer-quiz-images-${self:provider.stage}"
