
service: pdf2img

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  memorySize: 1792
  timeout: 90
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:getObject
    Resource: "arn:aws:s3:::quiztrainer-quiz-images-${self:provider.stage}/*"

functions:
  pdf2img:
    handler: pdf2img.execute
    events:
      - s3:
          bucket: "quiztrainer-quiz-images-${self:provider.stage}"
          event: s3:ObjectCreated:*
          rules:
            - suffix: .pdf

    environment:
      BUCKET: "quiztrainer-quiz-images-${self:provider.stage}"
