
service: pdf2img

custom:
   myStage: ${opt:stage, self:provider.stage}
   myEnvironment:
     HOSTURL:
       prod: "https://pdf2jpgs.com"
       dev: "http://localhost:3000"

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  environment:
    HOSTURL: ${self:custom.myEnvironment.HOSTURL.${self:custom.myStage}}
  region: us-west-2
  memorySize: 3008
  timeout: 180
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:getObject
    Resource: "arn:aws:s3:::quiztrainer-quiz-images-${self:provider.stage}/*"

functions:
  pdf2img:
    handler: pdf2img.execute
    events:
      - s3:
          bucket: pdf
          event: s3:ObjectCreated:*
          rules:
            - suffix: .pdf
      - s3:
          bucket: pdf
          event: s3:ObjectCreated:*
          rules:
            - suffix: .PDF

    environment:
      BUCKET: "quiztrainer-quiz-images-${self:provider.stage}"


resources:
  - ${file(resources/s3-bucket.yml)}
